# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
---
name: Build Firmware
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [nice_nano]
        shield: [left_half, right_half]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build firmware
        run: |
          docker run --rm -v ${GITHUB_WORKSPACE}:/workdir ghcr.io/zmkfirmware/zmk-dev-arm:stable \
            /bin/bash -c "west init -l app/ && west update && \
            west build -b ${matrix.board} -- -DSHIELD=${matrix.shield}"

      - name: Upload firmware
        uses: actions/upload-artifact@v2
        with:
          name: ZMK Firmware
          path: build/zephyr/zmk.uf2
